// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizMVC.Data;

#nullable disable

namespace QuizMVC.Migrations.Migrations
{
    [DbContext(typeof(QuizMvcDbContext))]
    [Migration("20230119103827_SeedDataIntoQuestionsTable")]
    partial class SeedDataIntoQuestionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizMVC.Models.Main.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizMVC.Models.Quiz.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QuizMVC.Models.Quiz.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "In which year did Psychedelic rock emerge?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5235)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Where is the lead singer of the Scorpions from?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5251)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Wise man said just walk this way, To the dawn of the ______",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5252)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "What was the name of Queen's vocalist?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5254)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "How many studio albums have Scorpions released?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5255)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Who is the lead singer of Epica?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5257)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "In 1991, Metallica released their album 'Metallica'. What animal is on the cover artwork? ",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5258)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Iron Maiden singer Bruce Dickinson is also a qualified pilot. True or false?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5259)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Guitarist Saul Hudson Is Better Known By Which Name?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5261)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            IsActive = false,
                            QuestionText = "Which classic rock album is sometimes said to be a soundtrack to The Wizard of Oz?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5262)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Which goddess inspired the Rolling Stones' logo?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5263)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Which Pink Floyd recording became the first rock album to be played in space?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5264)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "What was the first rock-n-roll song to hit #1 on the charts?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5266)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            IsActive = true,
                            QuestionText = "Which Aerosmith song was nominated for both Best Original Song and Worst Original Song?",
                            Updated = new DateTime(2023, 1, 19, 15, 38, 27, 157, DateTimeKind.Local).AddTicks(5267)
                        });
                });

            modelBuilder.Entity("QuizMVC.Models.Quiz.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("RightAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("QuizMVC.Models.Quiz.QuestionChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuestionChoices");
                });

            modelBuilder.Entity("QuizMVC.Models.Quiz.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Completed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("FinalScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
